### ISSUE TITLE
Adding categories to universalCashbackPercent

### ISSUE THREAD

**Issue by slimecastle** [andenacitelli/credit-card-bonuses-api#90]
Hi,
Would it be possible to add spend categories that are different than universal cashback to the API? Like for example, a card that earns 4% back on groceries. Would love to help out - I'm not sure what your mechanism is for populating all of the data you have. Sick API, by the way!

**Comment by andenacitelli** [comment]
Will unfortunately have to file this as a "will not implement". Would take a lot of time, make the interface much more complex, and kind of blur the focus of the API and Website (which are pretty explicitly oriented towards the bonuses themselves and not any kind of category spend consideration). 

I acknowledge it's not _totally_ orthogonal, seeing as you're coming at it from an angle of factoring it more accurately into the "opportunity cost" of spending on a new card instead of on your old one. Maybe you can just bump your current cashback by a little bit? 

For example, suppose you have the Amex Gold. 1% universal, 4% on groceries, best I recall. Maybe you can just approximate that your grocery spend is about 20% of your overall spend (or whatever the percentage is for you) and ballpark it at 1.5% "weighted" cashback, and call it a day?
